export type ExerciseInstruction = {
  steps: string[]
  mistakes: string[]
  tips: string[]
  breathing: string[]
  target: { primary: string; secondary: string }
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced'
}

export type Exercise = {
  id: string
  name: string
  muscles: string
  sets: string
  rest: string
  cue: string
  gif?: string
  equipment: string
  instruction: ExerciseInstruction
}

export type WorkoutDayId = '1' | '2' | '4' | '5' | '6'

export type WorkoutDay = {
  id: WorkoutDayId
  label: string
  focus: string
  tint: string
  exerciseIds: string[]
}

const beginner = 'Beginner' as const

export const exercises: Record<string, Exercise> = {
  hackSquat: { id:'hackSquat', name:'Hack Squat', muscles:'Quads · Glutes · Core', sets:'3 × 10–12', rest:'90 sec', equipment:'Hack squat machine', cue:'حطي ضهرك كله على المخدة، رجلك ثابتة، وانزلي بهدوء من غير ما ركبتك تدخل لجوه.', gif:'/exercises/squat.gif', instruction:{steps:['حطي ضهرك كله على ضهر الجهاز وخلي صدرك مرفوع.','ثبتي رجلك على المنصة بعرض كتفك تقريباً.','افتحي ركبتك في نفس اتجاه صوابع رجلك.','انزلي واحدة واحدة لحد مدى مريح.','اطلعي بدفع من الكعب ومن نص الرجل من غير ما ترمي الوزن.'],mistakes:['❌ متدخليش ركبتك لجوه.','❌ متشيليش ضهرك من على المخدة.','❌ متقفليش ركبتك جامد فوق.','❌ متنزليش بسرعة وتخلي الجهاز يحدفك.'],tips:['ابدئي بوزن خفيف عشان تتعلمي المسار.','ركزي إن الرجل كلها ثابتة على المنصة.','لو حسيتي ضغط في الركبة قللي العمق شوية.','النزول أبطأ من الطلوع.'],breathing:['خدي نفس وإنتي نازلة.','طلعي النفس وإنتي بتدفعي الجهاز لفوق.'],target:{primary:'الأفخاذ الأمامية',secondary:'المؤخرة، السمانة، البطن'},difficulty:beginner}},
  hipThrustA: { id:'hipThrustA', name:'Hip Thrust', muscles:'Glutes · Hamstrings', sets:'4 × 10–12', rest:'90 sec', equipment:'Bench / machine', cue:'ثبتي كتفك، دقنك لجوه شوية، واطلعي بعصر المؤخرة مش بتقويس ضهرك.', gif:'/exercises/hip-thrust.gif', instruction:{steps:['اسندي أعلى ضهرك على البنش وخلي رجلك تحت ركبتك.','دخلي دقنك سنة وخلي بصرك لقدام.','انزلي بالورك لتحت بهدوء.','اطلعي بالكعب لحد جسمك يبقى خط مستقيم.','اعصري المؤخرة ثانية فوق وانزلي تاني بتحكم.'],mistakes:['❌ متقوسيش ضهرك فوق.','❌ متبعديش رجلك قوي عن جسمك.','❌ مترفعيش بصدرِك وتنسي الحوض.','❌ متخبطيش الوزن في الأرض.'],tips:['فكري إن المؤخرة هي اللي بتقفل الحركة.','لو حاسة التمرين في الفخذ الأمامي بس، رجعي رجلك سنة.','خلي العدات نضيفة قبل ما تزودي وزن.','وقفة صغيرة فوق هتفرق جداً.'],breathing:['خدي نفس وإنتي نازلة.','طلعي النفس وإنتي طالعة وبتعصري المؤخرة.'],target:{primary:'المؤخرة',secondary:'الفخذ الخلفي، أسفل الظهر بثبات بسيط'},difficulty:beginner}},
  bulgarianSplitSquat: { id:'bulgarianSplitSquat', name:'Bulgarian Split Squat', muscles:'Glutes · Quads · Hamstrings', sets:'3 × 10 each leg', rest:'75–90 sec', equipment:'Bench / dumbbells', cue:'خدي خطوة ثابتة، نزلي ركبتك ورا لتحت، واطلعي من كعب الرجل اللي قدام.', gif:'/exercises/bulgarian-split-squat.gif', instruction:{steps:['حطي رجل ورا على البنش وخلي الرجل اللي قدام ثابتة.','انقلي وزنك على الرجل اللي قدام.','انزلي بجسمك لتحت كأنك مصعد مش لقدام.','خلي ركبتك ماشية مع صوابع رجلك.','اطلعي من كعب الرجل الأمامية بهدوء.'],mistakes:['❌ متخليش ركبتك تدخل لجوه.','❌ متقربيش رجلك من البنش قوي.','❌ متدفعيش من الرجل اللي ورا.','❌ متستعجليش عشان التوازن.'],tips:['ابدئي من غير دمبل لحد ما التوازن يثبت.','لو عايزة تركيز مؤخرة، ميلي بجسمك سنة لقدام.','خلي كل رجل تاخد نفس العدات.','مسكة خفيفة في حاجة جنبك عادي في الأول.'],breathing:['خدي نفس وإنتي نازلة.','طلعي النفس وإنتي بتطلعي من الرجل الأمامية.'],target:{primary:'المؤخرة والأفخاذ الأمامية',secondary:'الفخذ الخلفي، البطن للتوازن'},difficulty:beginner}},
  legExtension: { id:'legExtension', name:'Leg Extension', muscles:'Quads', sets:'3 × 12–15', rest:'60 sec', equipment:'Leg extension machine', cue:'ثبتي ضهرك في الكرسي وارفعي من قدام الفخذ، مش برعشة ولا زق مفاجئ.', gif:'/exercises/leg-extension.gif', instruction:{steps:['اقعدي وضهرك لازق في الكرسي.','ظبطي الرول فوق الرجل عند أول الكاحل.','امسكي المقابض وثبتي الحوض.','ارفعي رجلك لحد ما الفخذ يشد.','انزلي ببطء ومتسيبيش الوزن يقع.'],mistakes:['❌ مترفعيش الحوض من الكرسي.','❌ متقفليش الركبة بعنف فوق.','❌ متنزليش الوزن بسرعة.','❌ متخليش صوابع رجلك تلف لجوه.'],tips:['خلي الحركة من الركبة بس.','استني لحظة صغيرة فوق لو الوزن مناسب.','اختاري وزن يخلي آخر عدتين صعبين بس نضاف.','لو الركبة وجعتك قللي الوزن والمدى.'],breathing:['خدي نفس قبل الرفعة وإنتي تحت.','طلعي النفس وإنتي بتفردي رجلك لفوق.'],target:{primary:'الأفخاذ الأمامية',secondary:'عضلات حول الركبة للتثبيت'},difficulty:beginner}},
  hipAbduction: { id:'hipAbduction', name:'Hip Abduction Machine', muscles:'Side glutes · Hips', sets:'3 × 15–20', rest:'60 sec', equipment:'Hip abduction machine', cue:'افتحي رجلك بهدوء وخلي جسمك ثابت، من غير ما ترجعي بضهرك وتزقي بالجسم.', gif:'/exercises/hip-abduction-machine.gif', instruction:{steps:['اقعدي على الجهاز وخلي ضهرك ثابت.','حطي رجلك على المسندين من بره.','شدي بطنك وخلي صدرك مرفوع.','افتحي رجلك لبره لحد ما تحسي جنب المؤخرة شغال.','ارجعي ببطء ومتسيبيش الوزن يخبط.'],mistakes:['❌ مترجعيش بضهرك عشان تزودي المدى.','❌ متفتحيش بسرعة وترجعي أسرع.','❌ متشيليش وزن يخليكي تتحركي من مكانك.','❌ متسيبيش الركب تقفل وترتاح.'],tips:['فكري إن جنب المؤخرة هو اللي بيفتح الرجل.','عدي ببطء عشان الحرقان يظهر.','ثانية واحدة في آخر الفتحة كفاية.','المدى النضيف أهم من رقم الوزن.'],breathing:['خدي نفس وإنتي راجعة للمركز.','طلعي النفس وإنتي بتفتحي رجلك لبره.'],target:{primary:'المؤخرة الجانبية',secondary:'عضلات الحوض الخارجية'},difficulty:beginner}},
  standingCalfRaise: { id:'standingCalfRaise', name:'Standing Calf Raise', muscles:'Calves', sets:'3 × 15–20', rest:'45–60 sec', equipment:'Machine / step', cue:'اطلعي على صوابعك بمدى كامل، وقفي لحظة فوق، وانزلي لتمدد خفيف من غير تنطيط.', gif:'/exercises/standing-calf-raise.gif', instruction:{steps:['اقفي ورجلك بعرض الحوض وامسكي دعم لو محتاجة.','خلي ركبتك مفرودة بس مش مقفولة بعنف.','اطلعي على صوابعك لأعلى نقطة تقدري عليها.','اثبتي لحظة فوق.','انزلي ببطء لحد ما تحسي السمانة اتمددت.'],mistakes:['❌ متنطيش بسرعة.','❌ متطلعيش نص عدة بس.','❌ متخليش كعبك يهرب لجوه أو لبره.','❌ متحمليش على صوابعك بس من غير تحكم.'],tips:['اشتغلي مدى كامل حتى لو الوزن أقل.','خلي الطلوع نضيف والنزول أبطأ.','لو بتفقدي التوازن، امسكي الجهاز.','السمانة بتحب التكرارات الهادية.'],breathing:['خدي نفس وإنتي نازلة بالكعب.','طلعي النفس وإنتي طالعة على صوابعك.'],target:{primary:'السمانة',secondary:'عضلات القدم والكاحل'},difficulty:beginner}},
  latPulldownA: { id:'latPulldownA', name:'Lat Pulldown', muscles:'Lats · Upper back · Biceps', sets:'3 × 10–12', rest:'75–90 sec', equipment:'Cable machine', cue:'اسحبي الكوع لتحت ناحية جنبك، وخلي صدرك مرفوع من غير ما ترجعي بجسمك لورا.', gif:'/exercises/lat-pulldown.gif', instruction:{steps:['اقعدي وثبتي رجلك تحت المسند.','امسكي البار أوسع من كتفك سنة.','ارفعي صدرك وخلي كتفك بعيد عن ودنك.','اسحبي البار ناحية أعلى الصدر بالكوع.','ارجعي لفوق ببطء لحد ما ضهرك يتمدد.'],mistakes:['❌ متسحبيش ورا الرقبة.','❌ مترجعيش بجسمك لورا كتير.','❌ متشديش بإيدك بس.','❌ متسيبيش الوزن يطلع فجأة.'],tips:['تخيلي كوعك داخل في جيبك.','لو كتفك بيطلع لفوق قللي الوزن.','وقفة صغيرة تحت هتحسسك بضهرك.','متقفليش الحركة من الرسغ.'],breathing:['خدي نفس وإنتي سايبة البار يطلع.','طلعي النفس وإنتي بتسحبي لتحت.'],target:{primary:'الظهر الجانبي',secondary:'أعلى الظهر، البايسبس'},difficulty:beginner}},
  seatedCableRow: { id:'seatedCableRow', name:'Seated Cable Row', muscles:'Mid back · Lats · Biceps', sets:'3 × 10–12', rest:'75–90 sec', equipment:'Cable row machine', cue:'اقعدي طويلة واسحبي المقبض لبطنك، كتفك يرجع سنة من غير ما تحدبي.', gif:'/exercises/seated-cable-row.gif', instruction:{steps:['اقعدي ورجلك ثابتة على القاعدة.','امسكي المقبض وخلي ضهرك طويل.','ابدئي الحركة بسحب الكوعين لورا.','قربي المقبض من أسفل ضلوعك.','ارجعي لقدام ببطء من غير ما ضهرك يتكور.'],mistakes:['❌ متتحدبيش في الرجوع.','❌ متشديش بجسمك ورا وقدام.','❌ مترفعيش كتفك ناحية ودنك.','❌ متقصريش المدى عشان الوزن تقيل.'],tips:['خلي صدرك مفتوح طول التمرين.','حسي إن لوح الكتف بيتحرك براحة.','ثبتي بطنك كأن حد هيزقك.','اسحبي بالمرفق مش بالكف.'],breathing:['خدي نفس وإنتي بترجعي المقبض لقدام.','طلعي النفس وإنتي بتسحبي المقبض ناحيتك.'],target:{primary:'منتصف الظهر',secondary:'اللاتس، البايسبس، الكتف الخلفي'},difficulty:beginner}},
  chestPressMachine: { id:'chestPressMachine', name:'Chest Press Machine', muscles:'Chest · Triceps · Front delts', sets:'3 × 10–12', rest:'75–90 sec', equipment:'Chest press machine', cue:'كتفك ورا وتحت، ادفعي لقدام بهدوء، ومتقفليش كوعك جامد في آخر الحركة.', gif:'/exercises/chest-press-machine.gif', instruction:{steps:['اقعدي والضهر كله على الكرسي.','ظبطي المقابض في مستوى نص الصدر.','رجعي كتفك لتحت وورا.','ادفعي المقابض لقدام لحد ما دراعك يفرد تقريباً.','ارجعي ببطء لحد ما تحسي الصدر اتمدد.'],mistakes:['❌ متطلعيش كتفك لقدام.','❌ متقفليش كوعك بعنف.','❌ متسيبيش الوزن يرجع بسرعة.','❌ متقوسي ضهرك عشان تدفعي أكتر.'],tips:['خلي الرسغ فوق الكوع.','ابدئي بوزن يخليكي تتحكمي في الرجوع.','فكري في ضم الصدر مش زق الإيد بس.','لو كتفك وجعك قللي المدى.'],breathing:['خدي نفس وإنتي بترجعي المقابض.','طلعي النفس وإنتي بتدفعي لقدام.'],target:{primary:'الصدر',secondary:'الترايسبس، الكتف الأمامي'},difficulty:beginner}},
  lateralRaiseA: { id:'lateralRaiseA', name:'Dumbbell Lateral Raise', muscles:'Side delts', sets:'3 × 12–15', rest:'60 sec', equipment:'Light dumbbells', cue:'ارفعي بكوعك مش بإيدك، لحد مستوى الكتف بس، وانزلي أبطأ من الطلوع.', gif:'/exercises/dumbbell-lateral-raise.gif', instruction:{steps:['اقفي ثابتة وامسكي دمبل خفيف في كل إيد.','اثني كوعك سنة بسيطة.','ارفعي دراعك للجنب لحد مستوى الكتف.','خلي كتفك بعيد عن ودنك.','انزلي ببطء لحد جنب جسمك.'],mistakes:['❌ مترفعيش كتفك لفوق.','❌ متحدفيش جسمك عشان ترفعي.','❌ متطلعيش أعلى من كتفك كتير.','❌ متختاريش وزن يخلي الحركة تتلخبط.'],tips:['الكوع يقود الحركة مش الكف.','وزن خفيف هنا أحسن من وزن تقيل بشكل وحش.','ثبتي بطنك ومتتمايليش.','حاولي تحسي بجنب الكتف في كل عدة.'],breathing:['خدي نفس وإنتي بتنزيلي الدمبل.','طلعي النفس وإنتي بترفعي للجنب.'],target:{primary:'الكتف الجانبي',secondary:'أعلى الظهر للتثبيت'},difficulty:beginner}},
  rearDeltFly: { id:'rearDeltFly', name:'Rear Delt Fly', muscles:'Rear delts · Upper back', sets:'3 × 12–15', rest:'60 sec', equipment:'Machine / dumbbells', cue:'افتحي دراعك للجنب من الكتف الخلفي، ومتضميش رقبتك ولا ترفعي كتفك.', gif:'/exercises/rear-delt-fly.gif', instruction:{steps:['اقعدي على الجهاز أو ميلي بجسمك لو دمبل.','خلي صدرك ثابت وضهرك مفرود.','اثني الكوع ثنية صغيرة.','افتحي دراعك لورا وللجنب بهدوء.','ارجعي لنقطة البداية من غير ما الوزن يخبط.'],mistakes:['❌ متشديش برقبتك.','❌ متفرديش كوعك زيادة.','❌ مترجعيش جسمك لورا عشان تكملي العدة.','❌ متستخدميش وزن تقيل يخلي الضهر يتقوس.'],tips:['التمرين ده إحساسه صغير، عادي.','خلي الحركة واسعة بس مريحة للكتف.','فكري إنك بتبعدي إيدك عن بعض.','وقفة خفيفة في الآخر تساعدك تحسي بالكتف الخلفي.'],breathing:['خدي نفس وإنتي بترجعي لقدام.','طلعي النفس وإنتي بتفتحي دراعك.'],target:{primary:'الكتف الخلفي',secondary:'أعلى الظهر وبين لوح الكتف'},difficulty:beginner}},
  cableCurl: { id:'cableCurl', name:'Cable Curl', muscles:'Biceps · Forearms', sets:'3 × 10–12', rest:'60 sec', equipment:'Cable machine', cue:'ثبتي كوعك جنب جسمك وارفعي المقبض للصدر من غير ما ترجعي بضهرك.', gif:'/exercises/cable-curl.gif', instruction:{steps:['اقفي قدام الكابل وامسكي البار أو الحبل.','خلي كوعك لازق جنب جسمك.','ارفعي المقبض ناحية صدرك ببطء.','اعصري البايسبس لحظة فوق.','انزلي لحد ما دراعك يفرد تقريباً من غير رمي.'],mistakes:['❌ مترجعيش بضهرك عشان ترفعي.','❌ متطلعيش كوعك لقدام.','❌ متسيبيش الوزن يشد إيدك لتحت.','❌ متكسريش الرسغ.'],tips:['اختاري وزن يخلي الكوع ثابت.','نزلي في ثانيتين عشان العضلة تشتغل أكتر.','خلي كتفك مرتاح لتحت.','لو آخر عدتين صعبين بس نضاف يبقى الوزن مناسب.'],breathing:['خدي نفس وإنتي بتنزيلي المقبض.','طلعي النفس وإنتي بترفعيه لفوق.'],target:{primary:'البايسبس',secondary:'الساعد'},difficulty:beginner}},
  pallofPress: { id:'pallofPress', name:'Pallof Press', muscles:'Core · Obliques', sets:'3 × 12 each side', rest:'45–60 sec', equipment:'Cable / resistance band', cue:'ثبتي جسمك ضد شد الكابل، افردي إيدك لقدام من غير ما وسطك يلف.', gif:'/exercises/pallof-press.gif', instruction:{steps:['اقفي جنب الكابل وخلي المقبض عند صدرك.','ابعدي خطوة لحد ما تحسي شد خفيف.','ثبتي رجلك وشدي بطنك.','افردي إيدك لقدام ببطء.','ارجعي المقبض للصدر من غير ما جسمك يلف.'],mistakes:['❌ متسيبيش الكابل يلف وسطك.','❌ متقوسي ضهرك.','❌ متحبسيش نفسك.','❌ متختاريش مقاومة تخليكي تتمايلي.'],tips:['فكري إن جسمك عمود ثابت.','ابدئي بمقاومة خفيفة جداً.','كل ناحية تاخد نفس العدات.','لو صعب، وسعي وقفتك شوية.'],breathing:['خدي نفس والمقبض قريب من صدرك.','طلعي النفس وإنتي بتفردي إيدك لقدام.'],target:{primary:'عضلات البطن العميقة والجوانب',secondary:'الكتف والصدر للتثبيت'},difficulty:beginner}},
  walkingCardio: { id:'walkingCardio', name:'Walking or Incline Walk', muscles:'Heart · Legs · Glutes', sets:'20–30 min', rest:'As needed', equipment:'Treadmill / outdoors', gif:'/exercises/walking.gif', cue:'امشي بسرعة تقدري تتكلمي معاها، ولو على ميل خليه مريح ومش بيشد ركبتك.', instruction:{steps:['ابدئي أول 3 دقايق بسرعة هادية.','زودي السرعة أو الميل تدريجي.','خلي كتفك مرتاح ودراعك بيتحرك طبيعي.','امشي بإيقاع ثابت من غير جري.','اهدي آخر دقيقتين قبل ما توقفي.'],mistakes:['❌ متبدئيش بسرعة عالية مرة واحدة.','❌ متكبريش الميل لو ضهرك أو ركبتك اتضايقوا.','❌ متمسكيش الجهاز جامد طول الوقت.','❌ متخليش نفسك يقطع.'],tips:['اختاري شدة تقدري تتكلمي فيها.','جزمة مريحة هتفرق.','لو اليوم تقيل خليها 20 دقيقة بس.','المهم الاستمرارية مش إنك تخلصي مرهقة.'],breathing:['خدي نفس من مناخيرك على قد ما تقدري.','طلعي النفس بهدوء وسيبي النفس منتظم مع الخطوات.'],target:{primary:'القلب واللياقة',secondary:'الرجلين والمؤخرة بشكل خفيف'},difficulty:beginner}},
  rdl: { id:'rdl', name:'Romanian Deadlift', muscles:'Hamstrings · Glutes · Back', sets:'3 × 10', rest:'90 sec', equipment:'Dumbbells / barbell', cue:'زقي الحوض لورا والوزن قريب من رجلك، ولما تحسي شد في الخلفية اطلعي.', gif:'/exercises/rdl.gif', instruction:{steps:['اقفي والوزن قدام فخذك ورجلك ثابتة.','اثني ركبتك سنة بسيطة.','زقي الحوض لورا كأنك بتقفلي باب بضهرك.','نزلي الوزن قريب من رجلك لحد شد مريح في الخلفية.','اطلعي بعصر المؤخرة ورجعي الحوض لقدام.'],mistakes:['❌ متكوريش ضهرك.','❌ متنزليش الوزن بعيد عن رجلك.','❌ متحوليهاش سكوات بثني ركبة كتير.','❌ متبصيش في الأرض تحت رجلك مباشرة.'],tips:['ضهرك يفضل طويل ورقبتك مكملة الخط.','المدى حسب مرونة الخلفية مش لازم توصلي للأرض.','ابدئي بدمبل خفيفين.','لو حسيتي أسفل ضهرك أكتر من الخلفية قللي الوزن.'],breathing:['خدي نفس وإنتي بتنزيلي الوزن.','طلعي النفس وإنتي طالعة وبتعصري المؤخرة.'],target:{primary:'الفخذ الخلفي',secondary:'المؤخرة، الظهر للتثبيت'},difficulty:beginner}},
  hipThrustB: { id:'hipThrustB', name:'Hip Thrust', muscles:'Glutes · Hamstrings', sets:'3 × 10–12', rest:'90 sec', equipment:'Bench / machine', cue:'خلي ضلعك نازل وبطنك مشدودة، اطلعي لحد الحوض يستقيم بس من غير زيادة.', gif:'/exercises/hip-thrust.gif', instruction:{steps:['ثبتي أعلى ضهرك على البنش واختاري مكان رجل مريح.','خلي الركبة فوق الكعب تقريباً وإنتي فوق.','انزلي بالحوض لتحت بتحكم.','اطلعي لحد جسمك يبقى مستقيم.','اضغطي المؤخرة فوق وعدي ثانية.'],mistakes:['❌ متطلعيش زيادة وتقوسي أسفل ضهرك.','❌ متخليش ركبتك تفتح وتقفل عشوائي.','❌ متدفعيش من صوابع رجلك بس.','❌ متنزليش بسرعة.'],tips:['الكعب ثابت طول الحركة.','حطي فوطة أو باد لو البار مضايقك.','لو مش حاسة بالمؤخرة، جربي تقربي رجلك سنة.','سيبي الوزن يزيد بعد ما التحكم يبقى سهل.'],breathing:['خدي نفس وإنتي بتنزيلي الحوض.','طلعي النفس وإنتي بتدفعي لفوق.'],target:{primary:'المؤخرة',secondary:'الفخذ الخلفي والبطن للتثبيت'},difficulty:beginner}},
  seatedLegCurl: { id:'seatedLegCurl', name:'Seated Leg Curl', muscles:'Hamstrings', sets:'3 × 12', rest:'60–75 sec', equipment:'Seated leg curl machine', cue:'ثبتي فخذك في الكرسي واسحبي الكعب لتحت وورا، وارجعي ببطء.', gif:'/exercises/seated-leg-curl.gif', instruction:{steps:['اقعدي وضهرك ثابت في الجهاز.','ظبطي الرول فوق الكاحل من ورا.','ثبتي الفخذ تحت المسند.','اسحبي كعبك لتحت وورا لحد الخلفية تقبض.','ارجعي ببطء من غير ما الوزن يخبط.'],mistakes:['❌ مترفعيش الحوض من الكرسي.','❌ متسيبيش الوزن يرجع بسرعة.','❌ متستخدميش مدى قصير قوي.','❌ متشديش بصوابع رجلك بدل الكعب.'],tips:['فكري إن كعبك بيقرب من الكرسي.','خلي أول عدة بطيئة عشان تحسي بالمسار.','وقفة بسيطة تحت تقوي الإحساس.','لو حصل شد قوي قللي الوزن.'],breathing:['خدي نفس وإنتي بترجعي رجلك لقدام.','طلعي النفس وإنتي بتسحبي الكعب لورا.'],target:{primary:'الفخذ الخلفي',secondary:'السمانة بشكل بسيط'},difficulty:beginner}},
  walkingLunges: { id:'walkingLunges', name:'Walking Lunges', muscles:'Glutes · Quads · Hamstrings', sets:'3 × 12 each leg', rest:'90 sec', equipment:'Bodyweight / dumbbells', cue:'خدي خطوة مريحة، انزلي مستقيمة، واطلعي من الرجل اللي قدام من غير ما تتهزي.', gif:'/exercises/walking-lunges.gif', instruction:{steps:['اقفي مستقيمة وخدي خطوة لقدام.','انزلي الركبة اللي ورا ناحية الأرض بهدوء.','خلي ركبة الرجل الأمامية ماشية مع صوابعها.','ادفعي من الرجل اللي قدام واطلعي.','كملي الخطوة التالية بنفس التحكم.'],mistakes:['❌ متخليش الخطوة قصيرة قوي.','❌ متخليش ركبتك تخبط الأرض.','❌ متتمايليش يمين وشمال.','❌ متدفعيش من صوابع الرجل الأمامية بس.'],tips:['ابدئي بوزن الجسم الأول.','بصي لقدام عشان التوازن.','لو المكان ضيق اعمليها ثابتة مكانك.','كل عدة هادية أحسن من مشي سريع.'],breathing:['خدي نفس وإنتي نازلة في الخطوة.','طلعي النفس وإنتي بتدفعي وتطلعي.'],target:{primary:'المؤخرة والأفخاذ الأمامية',secondary:'الفخذ الخلفي والسمانة والتوازن'},difficulty:beginner}},
  cableKickback: { id:'cableKickback', name:'Cable Kickback', muscles:'Glutes', sets:'3 × 15 each leg', rest:'45–60 sec', equipment:'Cable ankle strap', gif:'/exercises/cable-kickback.gif', cue:'ثبتي جسمك وارجعي الرجل لورا من المؤخرة، مش من أسفل الضهر.', instruction:{steps:['ركبي حزام الكابل في كاحلك.','امسكي الجهاز وميلي سنة لقدام بضهر مفرود.','ثبتي الرجل اللي على الأرض.','ارجعي الرجل الشغالة لورا وفوق سنة.','ارجعيها قدام ببطء من غير ما الوزن يقع.'],mistakes:['❌ متقوسيش ضهرك عشان ترفعي أعلى.','❌ متلفيش الحوض للجنب.','❌ مترميش الرجل بسرعة.','❌ متخليهاش حركة مرجحة.'],tips:['مدى صغير ونضيف يكفي.','اعصري المؤخرة في آخر الحركة.','خلي صوابع رجلك متجهة لتحت أو سنة للخارج حسب راحتك.','لو حاسة أسفل ضهرك قللي الوزن فوراً.'],breathing:['خدي نفس وإنتي بترجعي الرجل لنقطة البداية.','طلعي النفس وإنتي بتدفعي الرجل لورا.'],target:{primary:'المؤخرة',secondary:'الفخذ الخلفي وثبات البطن'},difficulty:beginner}},
  seatedCalfRaise: { id:'seatedCalfRaise', name:'Seated Calf Raise', muscles:'Calves', sets:'3 × 15–20', rest:'45–60 sec', equipment:'Seated calf machine', gif:'/exercises/seated-calf-raise.gif', cue:'اطلعي بالكعب لفوق وإنتي قاعدة، وقفة صغيرة فوق ونزول هادي لتمدد تحت.', instruction:{steps:['اقعدي على الجهاز وحطي مقدمة رجلك على القاعدة.','خلي الركب تحت المسند ومش مضغوطة بزيادة.','نزلي الكعب لتحت لحد تمدد مريح.','اطلعي بالكعب لفوق لأعلى مدى.','اثبتي لحظة وبعدين انزلي ببطء.'],mistakes:['❌ متنطيش بالوزن.','❌ متعمليش نص مدى.','❌ متفتحيش رجلك بعيد عن وضع مريح.','❌ متسيبيش الكعب يقع لتحت فجأة.'],tips:['العدة البطيئة هنا تكسب.','ركزي على السمانة من جوه وتحت.','استخدمي وزن يخليكي توصلي للمدى كامل.','لو مفيش جهاز، اعمليها بدمبل على الركبة.'],breathing:['خدي نفس وإنتي بتنزيلي الكعب.','طلعي النفس وإنتي بترفعي الكعب لفوق.'],target:{primary:'السمانة',secondary:'عضلات الكاحل والقدم'},difficulty:beginner}},
  shoulderPressMachine: { id:'shoulderPressMachine', name:'Shoulder Press Machine', muscles:'Shoulders · Triceps', sets:'3 × 10–12', rest:'75–90 sec', equipment:'Shoulder press machine', cue:'ثبتي ضهرك في الكرسي وادفعي لفوق من غير ما ترفعي كتفك ناحية ودنك.', gif:'/exercises/shoulder-press-machine.gif', instruction:{steps:['اقعدي وضهرك لازق في المسند.','امسكي المقابض والكوع تحت الإيد تقريباً.','شدي بطنك وخلي رقبتك طويلة.','ادفعي لفوق لحد قبل قفل الكوع.','انزلي بالمقابض ببطء لمستوى مريح.'],mistakes:['❌ متقوسيش ضهرك عشان تدفعي.','❌ متقفليش كوعك جامد.','❌ مترفعيش كتفك ناحية ودنك.','❌ متنزليش أقل من قدرتك عشان الوزن تقيل.'],tips:['ابدئي بوزن يخلي المسار ثابت.','لو كتفك بيتضايق قللي النزول.','خلي الكوع قدام الجسم سنة مش مفتوح قوي.','التحكم في النزول أهم من الزق لفوق.'],breathing:['خدي نفس وإنتي بتنزيلي المقابض.','طلعي النفس وإنتي بتدفعي لفوق.'],target:{primary:'الكتف',secondary:'الترايسبس والجزء العلوي من الصدر'},difficulty:beginner}},
  singleArmCableRow: { id:'singleArmCableRow', name:'Single Arm Cable Row', muscles:'Lats · Mid back · Biceps', sets:'3 × 10–12 each side', rest:'60–75 sec', equipment:'Cable machine', cue:'اسحبي الكوع لورا جنب جسمك، وخلي جسمك ثابت من غير لف كتير.', gif:'/exercises/single-arm-cable-row.gif', instruction:{steps:['اقفي أو اقعدي قدام الكابل بمقبض واحد.','ثبتي جسمك وشدي بطنك.','سيبي كتفك يتمدد لقدام سنة في البداية.','اسحبي الكوع لورا ناحية جنبك.','ارجعي إيدك لقدام ببطء وكرري.'],mistakes:['❌ متلفيش وسطك عشان تسحبي.','❌ مترفعيش كتفك لفوق.','❌ متسحبيش بالبايسبس بس.','❌ متخليش ناحية أقوى من التانية تاخد عدات أكتر.'],tips:['ابدئي بالناحية الأضعف.','فكري في الكوع مش الكف.','خلي صدرك عالي بس من غير تقويس.','وقفة صغيرة ورا تساعدك تحسي بضهرك.'],breathing:['خدي نفس وإنتي بترجعي المقبض لقدام.','طلعي النفس وإنتي بتسحبي الكوع لورا.'],target:{primary:'الظهر الجانبي ومنتصف الظهر',secondary:'البايسبس والكتف الخلفي'},difficulty:beginner}},
  inclineChestPress: { id:'inclineChestPress', name:'Pec Deck Fly', muscles:'Chest · Front delts', sets:'3 × 10–12', rest:'75–90 sec', equipment:'Pec deck machine', cue:'افتحي صدرك وخلي ضهرك لازق، ضمي الدراعين قدامك بهدوء من غير ما كتفك يطلع لفوق.', gif:'/exercises/pec-deck-fly.gif', instruction:{steps:['اقعدي على جهاز الفراشة وخلي ضهرك كله لازق في المخدة.','ظبطي المقعد عشان إيدك تبقى في مستوى الصدر تقريباً.','افتحي صدرك وخلي كتفك نازل ورايح لورا سنة.','ضمي الدراعين قدامك بهدوء لحد ما تحسي الصدر اشتغل.','ارجعي افتحي ببطء من غير ما الوزن يخبط أو يشد كتفك.'],mistakes:['❌ متقربيش كتفك من ودنك.','❌ متفرديش كوعك جامد خالص.','❌ مترجعيش لورا بسرعة وتسيبي الوزن يشدك.','❌ متقفليش الحركة بإيدك بس وانتي ناسية الصدر.'],tips:['فكري إن صدرك هو اللي بيقرب الدراعين لبعض.','خلي الوزن متوسط عشان تحسي بالعضلة مش بالمفصل.','وقفة صغيرة وإنتي قافلة قدام هتحسسِك بالصدر أكتر.','لو الكتف وجعك قللي الفتحة وقللي الوزن.'],breathing:['خدي نفس وإنتي بتفتحي دراعك لورا.','طلعي النفس وإنتي بتضمي الدراعين قدامك.'],target:{primary:'الصدر',secondary:'الكتف الأمامي بثبات بسيط'},difficulty:beginner}},
  latPulldownB: { id:'latPulldownB', name:'V-Bar Lat Pulldown', muscles:'Lats · Upper back · Biceps', sets:'3 × 10–12', rest:'75–90 sec', equipment:'Cable machine with V-bar', cue:'امسكي الـ V-bar واسحبيه ناحية أعلى صدرك بالكوع، من غير ما ترجعي بجسمك لورا.', gif:'/exercises/lat-pulldown-different-grip.gif', instruction:{steps:['ركبي أو اختاري مقبض الـ V-bar على جهاز السحب.','ثبتي رجلك تحت المسند واقعدي طويلة.','خلي صدرك مرفوع وكتفك بعيد عن ودنك.','اسحبي الـ V-bar ناحية أعلى الصدر بالكوعين.','ارجعي لفوق ببطء وخلي ضهرك يتمدد براحة.'],mistakes:['❌ متسحبيش المقبض ناحية بطنك.','❌ مترجعيش بجسمك لورا عشان تكملي العدة.','❌ متقفليش كوعك جامد وإنتي طالعة.','❌ متسيبيش الوزن يشد كتفك لفوق.'],tips:['فكري إن كوعك نازل جنب جسمك.','لو حسيتيها في إيدك بس قللي الوزن.','وقفة صغيرة تحت هتخلي ضهرك يشتغل أحسن.','خلي القبضة مريحة والرسغ ثابت.'],breathing:['خدي نفس وإنتي سايبة الـ V-bar يطلع.','طلعي النفس وإنتي بتسحبيه لتحت ناحية صدرك.'],target:{primary:'الظهر الجانبي',secondary:'أعلى الظهر والبايسبس'},difficulty:beginner}},
  ropeTricepsPushdown: { id:'ropeTricepsPushdown', name:'Rope Triceps Pushdown', muscles:'Triceps', sets:'3 × 10–12', rest:'60 sec', equipment:'Cable rope', cue:'كوعك ثابت جنب جسمك، افردي الحبل لتحت وافتحيه سنة في الآخر.', gif:'/exercises/rope-triceps-pushdown.gif', instruction:{steps:['اقفي قدام الكابل وامسكي الحبل.','ثبتي كوعك جنب جسمك.','ميلي سنة بسيطة لقدام لو محتاجة توازن.','ادفعي الحبل لتحت لحد دراعك يفرد تقريباً.','افتحي طرف الحبل سنة وارجعي ببطء.'],mistakes:['❌ متحركيش كوعك لقدام وورا.','❌ مترفعيش كتفك.','❌ متقفليش الكوع بعنف.','❌ متسيبيش الوزن يطلع بسرعة.'],tips:['آخر الحركة اعصري الترايسبس ثانية.','وزن متوسط أحسن من جسم بيتحرك كله.','خلي الرسغ ثابت ومريح.','النزول القوي والرجوع الهادي هو المطلوب.'],breathing:['خدي نفس وإنتي بترجعي الحبل لفوق.','طلعي النفس وإنتي بتدفعي الحبل لتحت.'],target:{primary:'الترايسبس',secondary:'الساعد وثبات الكتف'},difficulty:beginner}},
  lateralRaiseB: { id:'lateralRaiseB', name:'Dumbbell Lateral Raise', muscles:'Side delts', sets:'3 × 12–15', rest:'60 sec', equipment:'Light dumbbells', cue:'خلي الوزن خفيف والحركة ناعمة، ارفعي للجنب كأنك بتبعدي الدراع عن جسمك.', gif:'/exercises/dumbbell-lateral-raise.gif', instruction:{steps:['امسكي الدمبل جنب جسمك واثني الكوع سنة.','ميلي بجسمك لقدام شعرة بسيطة لو أريح.','ارفعي الدراعين للجنب بهدوء.','وقفي عند مستوى الكتف.','انزلي في نفس المسار من غير خبط.'],mistakes:['❌ متطلعيش بإيدك لقدام بدل الجنب.','❌ متستخدميش رجلِك في الزق.','❌ متقربيش كتفك من ودنك.','❌ متعمليش عدات سريعة عشان تخلصي.'],tips:['عدي 2 ثواني وإنتي نازلة.','لو آخر العدات شكلها اتغير وقفي.','حافظي على رقبتك مرتاحة.','الكتف الجانبي بيبان مع الالتزام مش الوزن العالي.'],breathing:['خدي نفس وإنتي بتنزيلي.','طلعي النفس وإنتي بترفعي للجنب.'],target:{primary:'الكتف الجانبي',secondary:'الترابيس العلوية بشكل بسيط'},difficulty:beginner}},
  plank: { id:'plank', name:'Plank', muscles:'Core · Glutes · Shoulders', sets:'3 × 30–60 sec', rest:'45–60 sec', equipment:'Mat', cue:'جسمك خط واحد، بطنك ومؤخرتك مشدودين، ومتسيبيش وسطك يقع.', gif:'/exercises/plank.gif', instruction:{steps:['حطي كوعك تحت كتفك على الأرض.','ارجعي رجلك لورا وارفعي جسمك.','شدي بطنك كأنك بتقفلي سوستة.','خلي المؤخرة لا عالية قوي ولا واقعة.','اثبتي وتنفسك هادي لحد الوقت المطلوب.'],mistakes:['❌ متسيبيش وسطك ينزل.','❌ مترفعيش المؤخرة لفوق قوي.','❌ متحبسيش النفس.','❌ متبصيش لقدام قوي وتتعبي رقبتك.'],tips:['ابدئي بـ 30 ثانية نضيفة.','لو صعب، انزلي على الركب.','اضغطي الأرض بكوعك عشان كتفك يثبت.','وقفي لما الشكل يبوظ مش لما تتعبي خالص.'],breathing:['خدي نفس قصير وهادي طول الثبات.','طلعي النفس ببطء ومتقطعيش النفس.'],target:{primary:'البطن العميقة',secondary:'المؤخرة والكتف'},difficulty:beginner}},
  sidePlank: { id:'sidePlank', name:'Side Plank', muscles:'Obliques · Core · Glutes', sets:'3 × 30 sec each side', rest:'45 sec', equipment:'Mat', cue:'كوعك تحت كتفك وجسمك خط واحد، ارفعي جنبك من الأرض من غير ما الحوض يلف.', gif:'/exercises/side-plank.gif', instruction:{steps:['نامي على جنبك وحطي الكوع تحت الكتف.','خلي الرجلين فوق بعض أو واحدة قدام التانية.','ارفعي الحوض من الأرض.','شدي بطنك وخلي جسمك خط مستقيم.','اثبتي الوقت وبعدها بدلي الناحية.'],mistakes:['❌ متسيبيش الحوض يقع.','❌ متحطيش الكوع بعيد عن الكتف.','❌ متلفيش صدرك ناحية الأرض.','❌ متحبسيش النفس.'],tips:['لو صعب، اثني الركبة اللي تحت.','بصي لقدام وخلي الرقبة مرتاحة.','خلي الجنب اللي تحت هو اللي شايلك.','الجودة أهم من إنك تكملي الثواني بالعافية.'],breathing:['خدي نفس هادي وإنتي ثابتة.','طلعي النفس ببطء وحافظي على شد البطن.'],target:{primary:'جوانب البطن',secondary:'المؤخرة الجانبية والكتف'},difficulty:beginner}},
  deadBug: { id:'deadBug', name:'Dead Bug', muscles:'Deep core · Hip flexors', sets:'3 × 12', rest:'45 sec', equipment:'Mat', cue:'لزقي أسفل ضهرك في الأرض وحركي إيد ورجل عكس بعض ببطء.', gif:'/exercises/dead-bug.gif', instruction:{steps:['نامي على ضهرك وارفعي إيدك ورجلك لفوق.','اضغطي أسفل ضهرك في الأرض.','نزلي إيد ورجل عكس بعض ببطء.','ارجعيهم للنص من غير ما ضهرك يطلع.','بدلي الناحية وكملي بنفس الهدوء.'],mistakes:['❌ متسيبيش أسفل ضهرك يتقوس.','❌ متسرعيش الحركة.','❌ متنزليش الرجل أكتر من قدرتك.','❌ متنسيش النفس.'],tips:['لو ضهرك بيطلع، قصري مدى الرجل.','الحركة البطيئة هي التمرين.','خلي رقبتك مرتاحة على الأرض.','عدي كل ناحية بنفس التركيز.'],breathing:['خدي نفس وإنتي راجعة للنص.','طلعي النفس وإنتي بتنزيلي الإيد والرجل.'],target:{primary:'عضلات البطن العميقة',secondary:'مثنيات الورك وثبات الحوض'},difficulty:beginner}},
  birdDog: { id:'birdDog', name:'Bird Dog', muscles:'Core · Glutes · Back', sets:'3 × 12 each side', rest:'45 sec', equipment:'Mat', gif:'/exercises/bird-dog.gif', cue:'على أربع نقط، مدي إيد ورجل عكس بعض وخلي حوضك ثابت مش بيلف.', instruction:{steps:['انزلي على إيدك وركبك.','خلي الإيد تحت الكتف والركبة تحت الحوض.','شدي بطنك وخلي ضهرك مستقيم.','مدي إيد ورجل عكس بعض بهدوء.','ارجعي للنص وبدلي من غير ما جسمك يتهز.'],mistakes:['❌ متقوسيش ضهرك وإنتي بتمدي الرجل.','❌ متلفيش الحوض للجنب.','❌ مترفعيش الرجل أعلى من جسمك.','❌ متسرعيش وتفقدي التوازن.'],tips:['تخيلي على ضهرك كوباية مية ومش عايزاها تقع.','مدي بطول مش بارتفاع.','لو صعب، ابدئي بالرجل بس.','كل عدة خليها هادية وثابتة.'],breathing:['خدي نفس قبل ما تمدي.','طلعي النفس وإنتي بتمدي الإيد والرجل.'],target:{primary:'البطن وثبات الظهر',secondary:'المؤخرة والكتف'},difficulty:beginner}},
  reverseCrunch: { id:'reverseCrunch', name:'Reverse Crunch', muscles:'Lower abs · Core', sets:'3 × 15', rest:'45 sec', equipment:'Mat', cue:'ارفعي الحوض سنة لفوق من البطن، مش مرجحة رجل ولا زق بالسرعة.', gif:'/exercises/reverse-crunch.gif', instruction:{steps:['نامي على ضهرك وخلي الركب مثنية.','حطي إيدك جنبك على الأرض.','قربي الركب ناحية الصدر.','ارفعي الحوض سنة صغيرة من الأرض.','انزلي ببطء من غير ما الرجل تتهبد.'],mistakes:['❌ مترجحيش الرجل بقوة.','❌ متستخدميش رقبتك.','❌ متسيبيش أسفل ضهرك يخبط الأرض.','❌ متعمليش مدى كبير يوجع ضهرك.'],tips:['الحركة صغيرة بس مركزة.','فكري إن البطن بتلف الحوض لفوق.','لو صعب، قللي مدى النزول.','خلي العدات بطيئة عشان تحسي بالبطن.'],breathing:['خدي نفس وإنتي بتنزيلي الحوض.','طلعي النفس وإنتي بترفعي الركب والحوض لفوق.'],target:{primary:'أسفل البطن',secondary:'البطن العميقة ومثنيات الورك'},difficulty:beginner}},
  hollowHold: { id:'hollowHold', name:'Hollow Hold / Hollow Tuck', muscles:'Core', sets:'3 × 20–30 sec', rest:'45–60 sec', equipment:'Mat', gif:'/exercises/hollow-hold.gif', cue:'اضغطي ضهرك في الأرض واختاري النسخة السهلة بثني الركب لو الشكل بيتغير.', instruction:{steps:['نامي على ضهرك واضغطي أسفل ضهرك في الأرض.','ارفعي كتفك سنة عن الأرض.','ارفعي رجلك أو اثني ركبتك للنسخة الأسهل.','خلي بطنك مشدودة وإيدك ممدودة أو جنبك.','اثبتي من غير ما ضهرك يطلع.'],mistakes:['❌ متسيبيش ضهرك يتقوس.','❌ متشديش رقبتك بإيدك.','❌ متختاريش نسخة صعبة تخلي الشكل يبوظ.','❌ متحبسيش النفس.'],tips:['ابدئي Hollow Tuck والركب مثنية.','كل ما تبقي أقوى افردي الرجل أكتر.','لو ضهرك طلع، وقفي وارجعي أسهل.','ثبات نضيف 20 ثانية أحسن من 40 ثانية غلط.'],breathing:['خدي نفس قصير وإنتي ثابتة.','طلعي النفس ببطء مع شد البطن لتحت.'],target:{primary:'البطن الأمامية والعميقة',secondary:'مثنيات الورك وثبات الحوض'},difficulty:beginner}},
}

export const workoutDays: WorkoutDay[] = [
  { id:'1', label:'Lower A', focus:'Glutes, quads, and controlled lower-body strength', tint:'from-pink-500 to-rose-400', exerciseIds:['hackSquat','hipThrustA','bulgarianSplitSquat','legExtension','hipAbduction','standingCalfRaise'] },
  { id:'2', label:'Upper A', focus:'Back, chest, shoulders, arms, and anti-rotation core', tint:'from-fuchsia-500 to-pink-400', exerciseIds:['latPulldownA','seatedCableRow','chestPressMachine','lateralRaiseA','rearDeltFly','cableCurl','pallofPress'] },
  { id:'4', label:'Lower B', focus:'Glutes, hamstrings, lunges, and calves', tint:'from-pink-500 to-rose-400', exerciseIds:['rdl','hipThrustB','seatedLegCurl','walkingLunges','cableKickback','seatedCalfRaise'] },
  { id:'5', label:'Upper B', focus:'Shoulders, back, chest, triceps, and side delts', tint:'from-fuchsia-500 to-pink-400', exerciseIds:['shoulderPressMachine','singleArmCableRow','inclineChestPress','latPulldownB','ropeTricepsPushdown','lateralRaiseB'] },
  { id:'6', label:'Core Home', focus:'Beginner home core control and stability', tint:'from-rose-500 to-orange-300', exerciseIds:['plank','sidePlank','deadBug','birdDog','reverseCrunch','hollowHold'] },
]

export const meals = [
  { time:'Morning', title:'Breakfast', kcal:'', items:['Eggs','Whole wheat toast','Vegetables'], tone:'bg-amber-50 text-amber-700' },
  { time:'Snack', title:'Snack', kcal:'', items:['Fruit','Greek yogurt'], tone:'bg-fuchsia-50 text-fuchsia-700' },
  { time:'Midday', title:'Lunch', kcal:'', items:['Chicken, fish, or lean meat','Rice or potatoes','Large salad'], tone:'bg-emerald-50 text-emerald-700' },
  { time:'Pre-gym', title:'Pre-workout', kcal:'', items:['Banana or dates'], tone:'bg-blue-50 text-blue-700' },
  { time:'Evening', title:'Dinner', kcal:'', items:['Greek yogurt, cottage cheese, or tuna','Vegetables'], tone:'bg-pink-50 text-pink-700' },
]
